### ISSUE TITLE
Node server isn't reachable! every refresh

### ISSUE THREAD

**Issue by truelai** [turtle0x1/LxdMosaic#247]
I'm on the latest patch. In settings, _Current Version_ is blank and _New Version_ is 0.2.0

Every refresh of the page results in:

```
Node server isn't reachable!

You can try restarting the container or pm2 restart all
Without the node server you won't be able to get operation updates or connect to container consoles
```
Sometimes pm2 ls shows a stopped node. Sometimes it's running. If it's not running, it comes back by itself as expected.

**Comment by turtle0x1** [comment]
> Current Patch 

Is that 0.9.3

> Current Version is blank and New Version is 0.2.0

Thats not right, even on master branch you should get;

![Screenshot from 2020-09-17 15-22-10](https://user-images.githubusercontent.com/12494629/93484267-9e9f3300-f8f9-11ea-85ea-a44373f5312a.png)

Ill investigate that as a separate issue, that shouldn't be broken!

For node can you run `pm2 log 0` see if there any obvious errors!

**Comment by truelai** [comment]
`# pm2 log 0`

```
0|events  | { Error: Cannot find module 'sqlite3'
0|events  |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
0|events  |     at Module.Hook._require.Module.require (/usr/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:61:29)
0|events  |     at require (internal/modules/cjs/helpers.js:25:18)
0|events  |     at Object.<anonymous> (/var/www/LxdMosaic/node/events.js:14:13)
0|events  |     at Module._compile (internal/modules/cjs/loader.js:778:30)
0|events  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
0|events  |     at Module.load (internal/modules/cjs/loader.js:653:32)
0|events  |     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
0|events  |     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
0|events  |     at Object.<anonymous> (/usr/lib/node_modules/pm2/lib/ProcessContainerFork.js:32:23)
0|events  |     at Module._compile (internal/modules/cjs/loader.js:778:30)
0|events  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
0|events  |     at Module.load (internal/modules/cjs/loader.js:653:32)
0|events  |     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
0|events  |     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
0|events  |     at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
0|events  |     at startup (internal/bootstrap/node.js:283:19)
0|events  |     at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3) code: 'MODULE_NOT_FOUND' }
```

**Comment by turtle0x1** [comment]
ah `cd /var/www/LxdMosaic && npm i`

**Comment by turtle0x1** [comment]
I think this is covered well enough in https://github.com/turtle0x1/LxdMosaic/blob/master/UPGRADING.md so unless you run into a more specific issue with node ill close this for now!

**Comment by truelai** [comment]
```
root@lxd-mosaic:/var/www/LxdMosaic# git fetch --all
Fetching origin
root@lxd-mosaic:/var/www/LxdMosaic# git reset --hard origin/master
HEAD is now at 1d23ec7 Merge pull request #235 from turtle0x1/dependabot/npm_and_yarn/lodash-4.17.19
root@lxd-mosaic:/var/www/LxdMosaic# npm i && pm2 restart 0

> sqlite3@5.0.0 install /var/www/LxdMosaic/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Pre-built binaries not installable for sqlite3@5.0.0 and node@10.22.1 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error EACCES: permission denied, mkdir '/var/www/LxdMosaic/node_modules/sqlite3/lib/binding' 
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/var/www/LxdMosaic/node_modules/sqlite3/build'
gyp ERR! System Linux 4.15.0-111-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/var/www/LxdMosaic/node_modules/sqlite3/lib/binding/napi-v3-linux-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/var/www/LxdMosaic/node_modules/sqlite3/lib/binding/napi-v3-linux-x64" "--napi_version=6" "--node_abi_napi=napi" "--napi_build_version=3" "--node_napi_label=napi-v3"
gyp ERR! cwd /var/www/LxdMosaic/node_modules/sqlite3
gyp ERR! node -v v10.22.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/var/www/LxdMosaic/node_modules/sqlite3/lib/binding/napi-v3-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/var/www/LxdMosaic/node_modules/sqlite3/lib/binding/napi-v3-linux-x64 --napi_version=6 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/var/www/LxdMosaic/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Linux 4.15.0-111-generic
node-pre-gyp ERR! command "/usr/bin/node" "/var/www/LxdMosaic/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /var/www/LxdMosaic/node_modules/sqlite3
node-pre-gyp ERR! node -v v10.22.1
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/var/www/LxdMosaic/node_modules/sqlite3/lib/binding/napi-v3-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/var/www/LxdMosaic/node_modules/sqlite3/lib/binding/napi-v3-linux-x64 --napi_version=6 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@5.0.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sqlite3@5.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/lai/.npm/_logs/2020-09-17T16_24_20_955Z-debug.log
```

**Comment by truelai** [comment]
After installing missing dependencies:

```
lai@lxd-mosaic-local:/var/www/LxdMosaic$ composer install
Cannot create cache directory /home/lai/.composer/cache/repo/https---repo.packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /home/lai/.composer/cache/files/, or directory is not writable. Proceeding without cache
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Package operations: 30 installs, 0 updates, 0 removals

                                                                                       
  [RuntimeException]                                                                   
  /var/www/LxdMosaic/vendor/webmozart/assert does not exist and could not be created.  
                                                                                       

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...
```

**Comment by truelai** [comment]
I had this error: 

```
lai@lxd-mosaic-local:/var/www/LxdMosaic$ sudo npm i && sudo pm2 restart 0

> sqlite3@5.0.0 install /var/www/LxdMosaic/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Pre-built binaries not installable for sqlite3@5.0.0 and node@10.22.1 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error EACCES: permission denied, mkdir '/var/www/LxdMosaic/node_modules/sqlite3/lib/binding' 
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/var/www/LxdMosaic/node_modules/sqlite3/build'
gyp ERR! System Linux 4.15.0-115-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/var/www/LxdMosaic/node_modules/sqlite3/lib/binding/napi-v3-linux-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/var/www/LxdMosaic/node_modules/sqlite3/lib/binding/napi-v3-linux-x64" "--napi_version=6" "--node_abi_napi=napi" "--napi_build_version=3" "--node_napi_label=napi-v3"
gyp ERR! cwd /var/www/LxdMosaic/node_modules/sqlite3
gyp ERR! node -v v10.22.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/var/www/LxdMosaic/node_modules/sqlite3/lib/binding/napi-v3-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/var/www/LxdMosaic/node_modules/sqlite3/lib/binding/napi-v3-linux-x64 --napi_version=6 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/var/www/LxdMosaic/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Linux 4.15.0-115-generic
node-pre-gyp ERR! command "/usr/bin/node" "/var/www/LxdMosaic/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /var/www/LxdMosaic/node_modules/sqlite3
node-pre-gyp ERR! node -v v10.22.1
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/var/www/LxdMosaic/node_modules/sqlite3/lib/binding/napi-v3-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/var/www/LxdMosaic/node_modules/sqlite3/lib/binding/napi-v3-linux-x64 --napi_version=6 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@5.0.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sqlite3@5.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/lai/.npm/_logs/2020-09-17T16_36_31_741Z-debug.log

```
I resolved it with:

`# npm i -g sqlite3@4.0.1 --unsafe-perm`

**Comment by truelai** [comment]
```
1592 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 (node_modules/fsevents):
1593 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
1594 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
1594 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
1594 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
1594 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
1595 verbose stack Error: sqlite3@5.0.0 install: `node-pre-gyp install --fallback-to-build`
1595 verbose stack Exit status 1
1595 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
1595 verbose stack     at EventEmitter.emit (events.js:198:13)
1595 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
1595 verbose stack     at ChildProcess.emit (events.js:198:13)
1595 verbose stack     at maybeClose (internal/child_process.js:982:16)
1595 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
1596 verbose pkgid sqlite3@5.0.0
1597 verbose cwd /var/www/LxdMosaic
1598 verbose Linux 4.15.0-115-generic
1599 verbose argv "/usr/bin/node" "/usr/bin/npm" "i"
1600 verbose node v10.22.1
1601 verbose npm  v6.14.6
1602 error code ELIFECYCLE
1603 error errno 1
1604 error sqlite3@5.0.0 install: `node-pre-gyp install --fallback-to-build`
1604 error Exit status 1
1605 error Failed at the sqlite3@5.0.0 install script.
1605 error This is probably not a problem with npm. There is likely additional logging output above.
1606 verbose exit [ 1, true ]
```

**Comment by truelai** [comment]
Nevermind. I'm dumb and did used root where I shouldn't have.
