### ISSUE TITLE
WARN Hit error EACCES: permission denied, mkdir '/var/www/LxdMosaic/node_modules/sqlite3/lib/binding'

### ISSUE THREAD

**Issue by truelai** [turtle0x1/LxdMosaic#248]
I did an dbdump, saved my _sensitiveData_ dir, reinstalled using the script, imported the db, edited mysql user password, restored the _sensitiveData_ directory, made sure I was at the latest commit, successfully executed _composer install_ and then:

```
$ sudo npm i

> sqlite3@5.0.0 install /var/www/LxdMosaic/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Pre-built binaries not installable for sqlite3@5.0.0 and node@10.22.1 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error EACCES: permission denied, mkdir '/var/www/LxdMosaic/node_modules/sqlite3/lib/binding' 
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/var/www/LxdMosaic/node_modules/sqlite3/build'
gyp ERR! System Linux 4.15.0-115-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/var/www/LxdMosaic/node_modules/sqlite3/lib/binding/napi-v3-linux-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/var/www/LxdMosaic/node_modules/sqlite3/lib/binding/napi-v3-linux-x64" "--napi_version=6" "--node_abi_napi=napi" "--napi_build_version=3" "--node_napi_label=napi-v3"
gyp ERR! cwd /var/www/LxdMosaic/node_modules/sqlite3
gyp ERR! node -v v10.22.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/var/www/LxdMosaic/node_modules/sqlite3/lib/binding/napi-v3-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/var/www/LxdMosaic/node_modules/sqlite3/lib/binding/napi-v3-linux-x64 --napi_version=6 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/var/www/LxdMosaic/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Linux 4.15.0-115-generic
node-pre-gyp ERR! command "/usr/bin/node" "/var/www/LxdMosaic/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /var/www/LxdMosaic/node_modules/sqlite3
node-pre-gyp ERR! node -v v10.22.1
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/var/www/LxdMosaic/node_modules/sqlite3/lib/binding/napi-v3-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/var/www/LxdMosaic/node_modules/sqlite3/lib/binding/napi-v3-linux-x64 --napi_version=6 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@5.0.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sqlite3@5.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/lai/.npm/_logs/2020-09-17T18_51_17_621Z-debug.log
lai@lxd-mosaic-local:/var/www/LxdMosaic$ node-pre-gyp install --fallback-to-build
```
When I downgrade nodejs to 9.11.1, it succeeds.

**Comment by turtle0x1** [comment]
What OS & version is this ? I haven't seen this before & this isn't part of the installation LXDMosaic is usually responsible for

**Comment by turtle0x1** [comment]
Ive just tried this on ubuntu 18.04, It runs no problem

```
root@robo:/var/www/LxdMosaic# npm i

> sqlite3@5.0.0 install /var/www/LxdMosaic/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
[sqlite3] Success: "/var/www/LxdMosaic/node_modules/sqlite3/lib/binding/napi-v3-linux-x64/node_sqlite3.node" is installed via remote
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 44 packages from 87 contributors and audited 630 packages in 5.727s

4 packages are looking for funding
  run `npm fund` for details

found 2 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
```

But I dont think the sqlite3 supports node 10, so I really need to bump versions everywhere

**Comment by truelai** [comment]
This was on 18.04

Are you using node >10? The install script pulls 10.22.1 on 18.04. I'll bump my own as well. What version do you recommend?

**Comment by turtle0x1** [comment]
Hmm interesting, I think this has come from the use of sudo - I typically install this in a container 

what happens if you do `mdkir /var/www/LxdMosaic/node_modules/sqlite3/build && chmod -R 777 /var/www/LxdMosaic/node_modules/sqlite3/build && npm i` (the 777 is cause im lazy & its late)

**Comment by truelai** [comment]
What version of nodejs do you recommend to use? I'm currently on 9.11.1

**Comment by turtle0x1** [comment]
I use `v10.19.0` - `v10.22.0`

**Comment by truelai** [comment]
With 9.11.1:

```
# mkdir /var/www/LxdMosaic/node_modules/sqlite3/build && chmod -R 777 /var/www/LxdMosaic/node_modules/sqlite3/build && npm i
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

up to date in 6.018s
```

**Comment by turtle0x1** [comment]
looks like it fixed it, try refreshing the page

**Comment by turtle0x1** [comment]
sorry try `pm2 restart 0` and then check for errors `pm2 log 0`

**Comment by truelai** [comment]
0|events  | ReferenceError: URL is not defined
0|events  |     at Promise (/var/www/LxdMosaic/node/Hosts.js:53:22)
0|events  |     at new Promise (<anonymous>)
0|events  |     at Hosts.addDetails (/var/www/LxdMosaic/node/Hosts.js:41:12)
0|events  |     at loadHostsFromDb.then.mysqlResults (/var/www/LxdMosaic/node/Hosts.js:18:14)
0|events  |     at <anonymous>
0|events  |     at process._tickCallback (internal/process/next_tick.js:182:7)

**Comment by turtle0x1** [comment]
Your node version is `< 10`, see here 

https://stackoverflow.com/questions/52566578/url-is-not-defined-in-node-js

your going to have to modify the file `var URL = require('url').URL;`, im not really keen to support this, veresion 10 is the min!

**Comment by truelai** [comment]
Gotcha. 

```
# n rm 9.11.1
# n 10.0.0
# reboot
$ cd /var/www/LxdMosaic/
$ sudo npm i
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

up to date in 7.179s
$ sudo pm2 restart 0
Use --update-env to update environment variables
[PM2] Applying action restartProcessId on app [0](ids: 0)
[PM2] [events](0) ✓
┌─────┬───────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id  │ name      │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├─────┼───────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 0   │ events    │ default     │ 1.0.0   │ fork    │ 1208     │ 0s     │ 1    │ online    │ 0%       │ 22.2mb   │ root     │ disabled │
└─────┴───────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
```

All is well.
